### ISSUE TITLE
Postfix: enable `smtpd_forbid_bare_newline` and test with Delta Chat

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#149]
This setting is going to be enabled with Postfix >= 3.9 by default:
https://www.postfix.org/postconf.5.html#smtpd_forbid_bare_newline

It is mentioned in
https://www.mail-archive.com/postfix-users@postfix.org/msg100901.html
with relation to "SMTP Smuggling" attack.

> Setting "smtpd_forbid_unauth_pipelining = yes" may break legitimate
> SMTP clients that mis-implement SMTP, but such clients are exceedingly
> rare, especially when email is sent across the Internet.

There is no long-term proper fix for SMTP Smuggling yet and it does not affect us as we don't place non-Postfix SMTP services in front of Postfix: https://www.postfix.org/smtp-smuggling.html
It would just be nice to test `smtpd_forbid_bare_newline` with Delta Chat before it becomes the default.

There is one related issue in the core related to Autocrypt Setup Messages mixing line endings in MIME messages:
https://github.com/deltachat/deltachat-core-rust/issues/2792

**Comment by hpk42** [comment]
as soon as we enable the setting, and deploy it somewhere we can run the tests,
so it's an easy one-line change no?

**Comment by hpk42** [comment]
So how can we best get a newer postfix version? 
This was why i in the chat thought that we might have to build our own debs 
(not sure it needs to happen in CI, we don't need it continously)

**Comment by hpk42** [comment]
So nothing remains to be done for.this issue.  If we upgrade the base setup and recommend something else than debian 11 we will anyway test that it works.  Thanks for testing and verifying!
