### ISSUE TITLE
 Two thoughts to the concept "deploy via command"

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#154]
## Two thoughts to the concept "deploy via command"

First we have to clear up, that there are theoretical two devices: One device, where to _chatmail_ shall be installed, the other where from this git-repo is doing that.
You can choose, weather you do it on the same device or do it on two different devices. I strongly recommend, to do it not from the same account, e.g. root install it over root. This could causes security bugs, belonging to the hostprovider and other circumstandis.

Second: From the account, from where to install _chatmail_, best practice is to generate an install a ssh-key and copy the public-key to the root-account of the target-device:

``
ssh-keygen -f $file -t ed25519 &&
ssh-copy-id -i $file -p $port $login
``

Here ` $file ` is the path/to/the/key_file, the private key. Important: Uses the ed25519 algorithm, other produce bugs with python! The Port is given to ` $port ` (usualy 22) and the ` $login ` is usualy [root@chat.example.com](mailto:root@chat.example.com).

While copy the public-key to the target-device, you need to uses a password or another key pair, depending to the rules of your host-provider.

At last, it is necessary to write some things into ~/.ssh/config:

`` 
echo "Host $host" >> .ssh/config &&
echo "   Hostname "$host >> .ssh/config &&
echo "   User "$user >> .ssh/config &&
echo "   Port "$port >> .ssh/config &&
echo "   IdentityFile "$file >> .ssh/config &&
``

where `$host ` is the mailhost and ` $user ` is usually root.

**Comment by hpk42** [comment]
How a chatmail operator manages their ssh key is outside the scope what we chatmail install docs.  We just say that you need to be able to ssh login as root to your new vps.
