### ISSUE TITLE
Hardening sshd-config

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#170]
Carefull! The change of ssh-port is nessesary, but the port in ~/.ssh/config must be change either.

We need at least two free sessions!

my suggestion is here:

https://github.com/nudeldudel/chatmail/blob/2ae2e00cfab6ada5950e581ad6b1daaaa62dd835/cmdeploy/src/cmdeploy/sshd/sshd_conig

sorry for wrong filename

**Comment by hpk42** [comment]
If there is reason to go beyond Debian defaults for sshd-config please provide them.  I am closing this issue but any further replies will still be seen, no worries. 

Also, if you'd like to keep a "hardened" fork of chatmail, we'd be happy to link to it from the README
but for now i think we are generally relying on defaults whereever possible, and only adjust them if there is some concrete reasoning, not just some "abstract hardening".

**Comment by nudeldudel** [comment]
Ok, I will explain it in details, sometimes...

The other things round about the hardening are indeed more complicated. I
planed something... A Branche? 🤔 Good idea.

holger krekel ***@***.***> schrieb am Mi., 24. Jan. 2024,
16:04:

**Comment by n3ph** [comment]
Implementing solutions like [denyhosts](https://github.com/denyhosts/denyhosts) should be sufficient.

**Comment by nudeldudel** [comment]
Problem is allways: Solution after accident. I am not sure, that is wise.

I collected 40 attacks per hour on Mehl.cloud none on Daleth.cafe (only
this is harened)

OK, the easiest step and the first I ever do is to change the Port
somewhere over 10000. Many scanners don't scan over 10000.



Michael Gerlach ***@***.***> schrieb am Do., 25. Jan. 2024,
03:25:

**Comment by nudeldudel** [comment]
> If there is reason to go beyond Debian defaults for sshd-config please provide them. I am closing this issue but any further replies will still be seen, no worries.
> 
> Also, if you'd like to keep a "hardened" fork of chatmail, we'd be happy to link to it from the README but for now i think we are generally relying on defaults whereever possible, and only adjust them if there is some concrete reasoning, not just some "abstract hardening".

Mailsetrver are open and known. Chatmail is an attack onto comercial internet. So the IP-Adresses of chatmail instances are predestinated to be attacked.

- First point of attacking is the _SSH-Port._ TO change it over 22000 make it safer. 
- To verbose loglevel helps to indicate impacts.
- PermitRootLogin prohibit-password : it is much saver, only to use keys for root. Some Providers only allow keys for root-login. It should be standard.
- Brtueforce-Attacks will be harder with this to changes: MaxAuthTries 3 \ MaxSessions 2
- there is no need von keyboard-interactions as we don't use consoles with chatmail
- Any SSH-Forwarding has to be forbiten. As we mostly working in server-farms, our "neigbours" cann uses SSH-Forwarding discredititate our IPs. If they are on BlackList, chatmail doesn't work any longer.

Changes should be make by hand, as instance is public.
