### ISSUE TITLE
/etc/aliases.db missing after installation

### ISSUE THREAD

**Issue by M-Stenzel** [deltachat/chatmail#198]
"/var/log/mail.err" gets populated with many "chat postfix/smtps/smtpd: error: open database /etc/aliases.db: No such file or directory" entries, due to the fact that this file is missing.

The installation routine should include a "newaliases" command.

**Comment by missytake** [comment]
I moved /etc/aliases.db to /root/ on c2.testrun.org, so we can check whether the error appears there as well.

**Comment by missytake** [comment]
meanwhile, `/etc/aliases.db` was created on c2 automatically. `/var/log/mail.err` wasn't even created though; so I can't reproduce the issue.

Which linux distribution and which postfix version are you running?

**Comment by hpk42** [comment]
this seems to be stale. If `/etc/aliases.db: no such file or directory` happens again, let's create a new issue.
