### ISSUE TITLE
cmdeploy init fails if dnsutils isn't installed (dig isn't available)

### ISSUE THREAD

**Issue by missytake** [deltachat/chatmail#219]
If that error appears, we should

- use `nslookup` instead,
- or install dnsutils

other ideas?

**Comment by hpk42** [comment]
why do we use dig and not "dnspython" or similar python package?

**Comment by hpk42** [comment]
sorry, i now understand that all dns resolving happens on the remote side via unbound (and a flushed cache). wasn't aware of this before.
