### ISSUE TITLE
nginx.conf: Keep itself stable, but include a backdoor für other services

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#227]
I tested now several ways to put another service onto a chatmail instance.

To be honest, I don't think, it would be a good pratctise to change the ngingx.conf.j2 into the chatmail cmdeploy prozess.

Maybe it is possible to set one include-path into it, where additonal conf for nginx can be stored - on the target-device by the admin, for example a reverse proxy for another subdomain or something else - and are not touched, while cmdeploy does ist work.

My experience till now:

1. Second IP-Adress is to expensive and not really easier the keep all onto the same Address
2. Write into the conf under `cmdeploy/src/cmdeploy/nginx/nginx.conf.j2` is not a good idea. It is be changed by update chatmail and to find the bugs, you always have to switch between the two devices.

**Comment by hpk42** [comment]
"backdoor" is a term used in security discussions ;) 
"Customizing" a chatmail instance and nginx config could be done in a branch and you merge upstream changes from time to time.  Including an extra nginx file.would be the only change in that branch plus the addition of that  extra nginx config file..... This should minimize conflicts and is workable today.   Customizations of many other aspects (including postfix and dovecot, or the home page) can be done this way.   Most of chatmail development takes place I'm the (python) modules that we use with postfix and dovecot .... The nginx config, web layout or serving does not see many changes anyway.  So I am closing this issue :)
