### ISSUE TITLE
Start to tag releases w/ changelog

### ISSUE THREAD

**Issue by hagenest** [deltachat/chatmail#236]
There are issues I think we should close before our first tagged release:

- [x] #235 
- [x] #234 

Please feel free to add anything else :)

**Comment by missytake** [comment]
What will be the first one? 0.1.0?

**Comment by hpk42** [comment]
On Mon, Mar 25, 2024 at 09:52 -0700, missytake wrote:
> What will be the first one? 0.1.0?

1.1.0 i'd say -- we are in production with multiple instances, so >=1.0 makes sense.

**Comment by missytake** [comment]
1.1.0 was tagged :)
