### ISSUE TITLE
Build deb with dovecot delay patch

### ISSUE THREAD

**Issue by hagenest** [deltachat/chatmail#249]
We need a deb with dovecot with the patch for #72 included.

I first tried doing this at build.opensuse.org - but building debs with tons of additional backports from debian doesn't seem to be supported there - or at least not at all documented.

We now have (at least) 2 options:
- Build in the OBS anyway, but with dovecot-main + patch
  - Pro: We automatically get a PPA, relatively easy
  - Con: We build a bleeding-edge package for older dependencies in debian, this could lead to much more work in the long run
- Build the deb in the GitHub CI => Host a PPA on page.deltachat
  - Pro: We can easily fork the package from Debian
  - Con: We have to provide a PPA by ourself.

IMO option 2 would be the preferable option, at least until we decide to move chatmail to nixos :laughing: 
Will implement the building part now, we have to see how we best provide a repository then

**Comment by hagenest** [comment]
any ideas how we best provide a repository?

**Comment by hagenest** [comment]
This may sound stupid, but after your last message I searched again for some kind of documentation and now I got it. I tried to build the package like described here: https://www.sidorenko.io/post/2016/05/build-packages-with-openbuild-service/

This did not work - but I now found this page (which for some reason doesn't seem indexed by search engines): https://en.opensuse.org/openSUSE:Build_Service_Debian_builds

And this explanation actually works :) So yeah, I'm now all in favor of the first option again.
Apologies for being very confidently incorrect when opening this issue :sweat_smile:

**Comment by hagenest** [comment]
Hooray, we have a deb and repo: https://download.opensuse.org/repositories/home:/deltachat/Debian_12/

https://build.opensuse.org/package/show/home:deltachat/

Here is the explanation for adding the repo, I'll add instructions tomorrow: https://en.opensuse.org/openSUSE:Build_Service_Debian_builds#Adding_repository_signing_key

**Comment by hpk42** [comment]
https://build.opensuse.org/package/show/home:deltachat/ gives 404
and i still don't quite get what is the source for https://download.opensuse.org/repositories/home:/deltachat/Debian_12/

the input flowing into the build-process there should be committed into a separate "deltachat/debian-builds" one  with a proper README -- along with being explicit what kind of permissions/passwords are neccessary. 
Ideally, a 3rd party should be able to build their own debian-packages (without opensuse) and use that for their chatmail service.

**Comment by hagenest** [comment]
The obs is doing odd things - it automatically creates a signing key, but does not sign the deb. The docs imply that it should do that. I'll ask around in the obs matrix channel; until I get a reply this is issue is blocked. 

We can use the deb, but for that we would have to disable the signing check in apt and that doesn't seem a reasonable solution.

**Comment by hagenest** [comment]
okay, now it finally works. @link2xt, you are correct. And I finally found out how to add the repository. and the key in a way that debian likes. Apparently using apt-add-repository, editing `/etc/apt/sources.list.d/obs.sources` or creating a new sources file does not work. But creating `/etc/apt/sources.list` works.

So, here are the steps:

Add our signing key to the apt keyring

```
curl https://build.opensuse.org/projects/home:deltachat/signing_keys/download?kind=gpg | sudo gpg --dearmor -o /etc/apt/keyrings/obs-home-deltachat.gpg
```
Add to `/etc/apt/sources.list`:

```
deb [signed-by=/etc/apt/keyrings/obs-home-deltachat.gpg] https://download.opensuse.org/repositories/home:/deltachat/Debian_12/ ./
```

Install dovecot :partying_face: 

```
sudo apt update
sudo apt install dovecot-core
```

**Comment by hagenest** [comment]
happy to announce that we now have an ARM build for dovecot too :) There is a debian runnner for ARM in the OBS, it's just that the docs are wrong, lol
