### ISSUE TITLE
Make it impossible to create IMAP folders

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#253]
I have searched Dovecot mailing list archives, recommended solution is to setup ACL plugin: https://doc.dovecot.org/configuration_manual/acl/

We need to deny creation of new folders and make a test that tries to create folders like "DeltaChat", "Trash", "Spam", "INBOX/DeltaChat", "INBOX.DeltaChat" etc. and fails every time.

**Comment by missytake** [comment]
Why do we need to do that?
