### ISSUE TITLE
Two more variables into the chatmail.ini

### ISSUE THREAD

**Issue by ghost** [deltachat/chatmail#268]
As chatmail is recommended for small groups, the compliance into this group can it make affordable to change the maximal size of the message and the time to delete an inactive account, too. 

Please add these two variables into chatmail.ini if it is possible:

max_size =              # maximal size for a message in megabyte
time_to_delete =    # an inactive acoount in days

Thank you!

**Comment by hpk42** [comment]
On Tue, Apr 02, 2024 at 21:25 -0700, Dorfzwockel wrote:
> As chatmail is recommended for small groups, the compliance into this group can it make affordable to change the maximal size of the message and the time to delete an inactive account, too. 
> 
> Please add these two variables into chatmail.ini if it is possible:
> 
> 
> max_size =              # maximal size for a message in megabyte

makes sense (although i'd name is `max_message_size`). 

> time_to_delete =    # an inactive acoount in days

what would be your definition of "inactive"? 

I'd suggest "since last login" ... not sure if we already have this info easily
but shouldn't be too hard to add if not.

**Comment by nudeldudel** [comment]
That's what I mean. Since last sucsessfull login, or since last interaction
with dovecot or something like that...

holger krekel ***@***.***> schrieb am Mi., 3. Apr. 2024,
11:16:

**Comment by hagenest** [comment]
We have to think about the best way to introduce new options into chatmail.ini without breaking existing deployments.

**Comment by thenktor** [comment]
So now there is no way to (automatically) delete inactive accounts?

**Comment by hpk42** [comment]
since https://github.com/deltachat/chatmail/pull/350 is merged accounts are automatically deleted and there is a `delete_inactive_users_after` config option now.  So this issue here is partly addressed.
