### ISSUE TITLE
Writes to source.list every time

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#272]
--> Starting operation: Add DeltaChat OBS home repository to sources.list
    [koffer.szh.homes] Success

This writes the same line to source.list every time and produces a timeout bug during apt update.

**Comment by hagenest** [comment]
Thank you for the report @nudeldudel and apologies for the late reply. I was able to reproduce this bug, looking into it now :)

**Comment by nudeldudel** [comment]
No worries, thanks for the update!

Christian Hagenest ***@***.***> schrieb am Fr., 17. Mai 2024,
14:43:

**Comment by nudeldudel** [comment]
Great!

Christian Hagenest ***@***.***> schrieb am Fr., 17. Mai 2024,
17:45:
