### ISSUE TITLE
Authentication from Postfix to Dovecot is flaky

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#273]
Delta chat core CI sometimes fails to create an account with "transient: 4.7.0 Temporary authentication failure: Connection lost to authentication server" error when running Python tests.

In Postfix logs I found this:
```
Apr 25 11:39:24 nine postfix/smtps/smtpd[986002]: warning: unknown[52.159.136.144]: SASL PLAIN authentication failed: (reason unavailable), sasl_username=$ci-jv34ug@nine.testrun.org
Apr 25 11:39:24 nine postfix/smtps/smtpd[986002]: too many errors after AUTH from unknown[52.159.136.144]
Apr 25 11:39:24 nine postfix/smtps/smtpd[986002]: disconnect from unknown[52.159.136.144] ehlo=1 auth=0/1 commands=1/2
```

So it seems Dovecot sometimes get overloaded by authentication requests from Postfix.
On Dovecot side I don't see anything related in the log, so it looks like socket queue got overloaded and connection failed on the kernel level without reaching dovecot process.

If possible we should increase queue size on dovecot socket or make authentication processing faster somehow.

**Comment by hpk42** [comment]
Since #379 removed the doveauth sqlite table, and IO can easily happen concurrently (previously the sqlite-write lock serialized all accesses) i suspect there will be less or no authentication problems from postfix. 
If not, let's open a new issue.
