### ISSUE TITLE
Revise privacy policy to talk about "default delta chat onboarding"

### ISSUE THREAD

**Issue by hpk42** [deltachat/chatmail#280]
The upcoming delta chat 1.46 "create chat profile" view links to the privacy policy of this repository which suddenly talks about "nine.testrun.org" without giving a direct hint why (because it's the default onboarding server for Delta Chat) and which alternatives exist (link to https://delta.chat/en/chatmail".   Other chatmail servers have adapted the start page anyway, so we can just change things here in the repo or make a particular "nine.testrun.org" intro blurb in the jinja templatee.

**Comment by missytake** [comment]
Fixed by https://github.com/deltachat/chatmail/pull/307
