### ISSUE TITLE
METRICS doesn't work

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#282]
As I installed the new instance, acesttoi.fr, metrics doesn't work. I did no changes to the main branch. 

Browser shows "nginx 404"….

**Comment by missytake** [comment]
Hm, what does your `/etc/cron.d/chatmail-metrics` file say? It's supposed to create `/var/www/html/metrics`, which apparently doesn't exist.

**Comment by nudeldudel** [comment]
The command outof crontab works fine by hand, then the site works.

Some bug with cron? 🤔

missytake ***@***.***> schrieb am Mo., 6. Mai 2024, 13:17:

**Comment by nudeldudel** [comment]
Yes, I agree. Good idea!

link2xt ***@***.***> schrieb am Di., 7. Mai 2024, 17:54:

**Comment by hagenest** [comment]
pyinfra doesn't support the creation of systemd timers, so we just copy one over with file.put, right?

**Comment by nudeldudel** [comment]
Correct.

Christian Hagenest ***@***.***> schrieb am Sa., 18. Mai 2024,
18:34:

**Comment by missytake** [comment]
> Or we should switch to using systemd timer as we depend on systemd anyway.

I don't have a problem with it, but it makes it slightly harder for the openBSD folks.

**Comment by missytake** [comment]
There are more cronjobs, which also would need a systemd timer (when they fail it's less obvious, but even more problematic).

Or we just install cron, which would be less work.

**Comment by hagenest** [comment]
currently deliberating if my love for systemd outweighs my love for easy solutions

**Comment by hpk42** [comment]
On Sun, May 19, 2024 at 04:42 -0700, missytake wrote:
> > Or we should switch to using systemd timer as we depend on systemd anyway.
> 
> I don't have a problem with it, but it makes it slightly harder for the openBSD folks.

Good point. We rely on systemd already but is there real need to use it as replacement for Cron?

**Comment by hagenest** [comment]
only reason afaik is that cron is deprecated on Debian 12 and it may not be installed on all systems by default. Using systemd would mean we need one fewer dependency.

But on most of our users systems, cron was installed anyways. It may only happen on Raspbian.

**Comment by nudeldudel** [comment]
Not on Raspian, there cron is usualy installed by default.

Especially Dietpi, which is the better OS for Raspis and Co uses cron
itself.

Some VPS setups don't install cron - and other things.

Christian Hagenest ***@***.***> schrieb am So., 26. Mai 2024,
19:42:
