### ISSUE TITLE
Stop logging IP addresses

### ISSUE THREAD

**Issue by missytake** [deltachat/chatmail#294]
Right now, we are logging IP addresses of users in several locations:

- `journalctl -f -u dovecot`
- `journalctl -u postfix@-.service -f`
- `journalctl --facility=2` in general (showing all mail related log messages in journald)
- `/var/log/nginx/access.log`
- `/var/log/nginx/error.log`
- ...other places? don't think so.

postfix (and dovecot as well I think) doesn't allow to specify a log format. Three possible solutions:

1. it allows to specify a log file though. Maybe we could write a log daemon which receives postifx logs and rewrites them before saving them to disk/journald.
2. we could use nginx in stream mode as a reverse TCP proxy, at least on the port(s) Delta Chat connects to. Then all IPs postfix sees would be "localhost". Could this cause problems with validating MTA-STS or reverse DNS lookups though?
3. we could pass the log lines to rsyslog, use an rsyslog config template to scrub the IP addresses from the log line... and maybe even pass them to journald again in the end?

**Comment by missytake** [comment]
Config templates seem to be able to rewrite log messages, if I'm understanding this correctly: https://stackoverflow.com/questions/52636918/is-there-a-way-parse-log-messages-using-rsyslog-config-and-transform-them-to-str

**Comment by hagenest** [comment]
related: such a feature was proposed for journald, but is "out-of-scope". :<

https://github.com/systemd/systemd/issues/2447

**Comment by missytake** [comment]
autistici is forwarding the logs from journald to rsyslog: https://www.autistici.org/orangebook2/orangebook2-en.html#logging

We can probably look up in https://git.autistici.org/ai3/ how they do it exactly

**Comment by hagenest** [comment]
okay, so we set journald to memory and define rsyslog as the output. Before being saved into rsyslog, the logs are filtered / anonymized via rsyslog-filters. Do we stop here, or do we want to collect our logs in a more ergonomic logging service?

For our own deployment it could be nice to put them into a central grafana-compatible DB, but what do we do for chatmail?

**Comment by hagenest** [comment]
In any case, I'll take c2.testrun.org for today and try to implement the clear stuff :) If rsyslog isn't comfortable enough, we still can forward the logs further

**Comment by missytake** [comment]
...or we just store *all logs* only in memory. Then we don't need to sanitize them at all. Should be fine, it's just one line of journald config.

Oh, and we need to convince nginx to log to journald instead of /var/log/nginx.
