### ISSUE TITLE
delete_mails_after = 40 is too high

### ISSUE THREAD

**Issue by missytake** [deltachat/chatmail#298]
@hagenest just ran into the 100MB limit.

Also, GDPR has a frist of 1 month, which is why it makes sense to keep mails less than that if we want to have a minimalist privacy policy. Maybe 20 days?

Should this be the new default or should we just change it for nine.testrun.org?

**Comment by hagenest** [comment]
I think 20 is reasonable, if you agree, we can just merge the PR :)
