### ISSUE TITLE
Steps for Chatmail when IPv6 support is disabled in OS

### ISSUE THREAD

**Issue by roughnecks** [deltachat/chatmail#306]
Hello,

We had a situation with our VPS's host because they aren't letting customers set a PTR for IPv6.
So the choice was pretty simple, disable IPv6 entirely on chatmail.

First I edited `/etc/default/grub` and added `ipv6.disable=1` to:

```
GRUB_CMDLINE_LINUX_DEFAULT=
GRUB_CMDLINE_LINUX=
```

while preserving the other settings. Just add the new option at the end of those configurations (space separated options)

Then I rebooted the server and noticed I couldn't connect anymore to chatmail.
Dovecot and nginx were down because both tried to listen to the now unsupported IPv6 address family.

Fix for nginx is easy, just remove the two `listen [::]:443` lines in /etc/nginx/nginx.conf and restart the service.
Fix for Dovecot was to add a new line to /etc/dovecot/dovecot.conf so that it only listens to IPv4:

`listen = *`

Last, when I tried to run `mailq` I also got this warning from Postfix, which I hadn't noticed before:

```
mailq: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
postqueue: warning: inet_protocols: disabling IPv6 name/address support: Address family not supported by protocol
Mail queue is empty
```

To fix that I edited /etc/postfix/main.cf, changing from:

`inet_protocols = all`

to

`inet_protocols = ipv4`

Again, restart dovecot and postfix when done.
Everyone seem extremely silent this evening on our server, but I believe everything is working alright, DC says it's connected and mailq is empty after sending a few messages myself..

**Comment by hpk42** [comment]
> We had a situation with our VPS's host because they aren't letting customers set a PTR for IPv6. So the choice was pretty simple, disable IPv6 entirely on chatmail.

do you need this PTR record for interop with other e-mail servers? 
chatmail's postfix does not care about reverse-ip lookup FWIW.

**Comment by roughnecks** [comment]
I think it's pretty recommended for any email server to have PRT record(s) and we have users from everywhere, not just chatmail.

**Comment by missytake** [comment]
Also, there are other chatmail operators who requested this

**Comment by roughnecks** [comment]
I believe if v6 support is not disabled, the server will always try it before v4, so it will be slower in responses before falling back to v4.

**Comment by roughnecks** [comment]
If you have to send mail to some IPv6-enabled server, I believe v6 will always be tried first (resolution, connect etc..), so before it fails and v4 fallback kicks in, you lost time and resources. How many? I cannot say, but for a busy chatmail maybe "enough".
