### ISSUE TITLE
scripts/initenv.sh update-deps doesn't work

### ISSUE THREAD

**Issue by nudeldudel** [deltachat/chatmail#313]
- Operating System (Linux Debian 12 latest update):

- Expected behavior: scripts/initenv.sh should init venv
- Actual behavior: venv: error: unrecognized arguments: --upgrade-deps
- Steps to reproduce the problem: reinstall python3-venv

- Logs:  which logs?

**Comment by hagenest** [comment]
Thanks for the bug report!

I just tried reproducing the issue and wasn't able to. I set up a clean Debian 12 container and ran only the following commands:
```
sudo apt update
sudo apt upgrade
sudo apt install python3.11-venv
scripts/initenv.sh
```
This worked on my machine without a problem. 

Can you post the entire output of your terminal when you `scripts/initenv.sh`?

**Comment by nudeldudel** [comment]
No, just the usage-Text and the error. --upgrade-depends  seamed to be replaced with --upgrades. That's all.

BTW: The bug happend while upgrading mehl.cloud. It damaged the generated files und directories by using git. 

I don't like git. It is microsoft....
