### ISSUE TITLE
python: migrate away from `crypt` library

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#318]
`crypt` is removed in Python 3.13 which is currently in beta.

**Comment by hagenest** [comment]
I suppose we should replace it with hashlib?

**Comment by hagenest** [comment]
ah, if we already use that, sure! I was thinking that maybe passlib would be an option too, but best to keep dependencies low.

**Comment by hagenest** [comment]
wait, we are doing our crypto with a random library with 2 github stars? 
Maybe we should use passlib instead? It's recommended in the crypt docs: https://docs.python.org/3/library/crypt.html

**Comment by hpk42** [comment]
I am not sure this whole crypt->passlib or other mechanism is really worth it. 
Chatmail is based on debian 12, and that uses python 3.11. 
By the time debian packages python 3.13 and we switch to debian 13 or so, 
we might have ported our python code to Rust already. 
So i suggest to close both this issue and the PR, and revisit it next year, or in the context of a Debian 13 upgrade of chatmail.

**Comment by missytake** [comment]
Who knows, maybe there is a better crypt replacement then.

**Comment by hagenest** [comment]
yeah, makes sense I guess

**Comment by missytake** [comment]
> So i suggest to close both this issue and the PR, and revisit it next year, or in the context of a Debian 13 upgrade of chatmail.

We're still working on it because it is basically finished and only the CI is broken. If we realize it is not actually finished we will probably close it.

**Comment by adbenitez** [comment]
I initially tried switching to hashlib that seems to be the recommended lib in the standard lib, but crypt does random salting while hashlib doesn't and in theory that makes it vulnerable to rainbow-something attacks so I decided to go with the smaller change
