### ISSUE TITLE
 dovecot-core : Depends: libicu72 (>= 72.1~rc-1~) but it is not installable, on Ubuntu 24.04

### ISSUE THREAD

**Issue by eccsatan** [deltachat/chatmail#332]
--> Starting operation: Install Dovecot
    [nine.testrun.org] Reading package lists...
    [nine.testrun.org] Building dependency tree...
    [nine.testrun.org] Reading state information...
    [nine.testrun.org] Some packages could not be installed. This may mean that you have
    [nine.testrun.org] requested an impossible situation or if you are using the unstable
    [nine.testrun.org] distribution that some required packages have not yet been created
    [nine.testrun.org] or been moved out of Incoming.
    [nine.testrun.org] The following information may help to resolve the situation:
    [nine.testrun.org]
    [nine.testrun.org] The following packages have unmet dependencies:
    [nine.testrun.org]  dovecot-core : Depends: libicu72 (>= 72.1~rc-1~) but it is not installable
    [nine.testrun.org] E: Unable to correct problems, you have held broken packages.
    [nine.testrun.org] Error: executed 0/1 commands
--> pyinfra error: No hosts remaining!
Traceback (most recent call last):
  File "/mnt/d/chatmail/chatmail/venv/bin/cmdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/d/chatmail/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 300, in main
    res = args.func(args, out, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/chatmail/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 67, in run_cmd
    out.check_call(cmd, env=env)
  File "/mnt/d/chatmail/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 224, in check_call
    return subprocess.check_call(arg, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pyinfra --ssh-user root nine.testrun.org /mnt/d/chatmail/chatmail/cmdeploy/src/cmdeploy/deploy.py' returned non-zero exit status 1.

**Comment by eccsatan** [comment]
I am planning to deploy on the internal network, so I have used the domain nine.testrun.org here for user convenience.

**Comment by hpk42** [comment]
What output do you get if you login to the target machine and do 

    sudo apt install dovecot-imapd

?

**Comment by hpk42** [comment]
thanks for reporting back. 

@eccsatan please open a new issue if the problem persists and do provide the output of a manually executed "sudo apt install dovecot-imapd" on the target host. thanks!

**Comment by fluoriteByte** [comment]
randomly got this issue today when updating my chatmail service, libicu72 isn't in ubuntu's repos and i don't know why it needs it now all of a sudden? had to install it from debian's repos :/

**Comment by missytake** [comment]
> randomly got this issue today when updating my chatmail service, libicu72 isn't in ubuntu's repos and i don't know why it needs it now all of a sudden? had to install it from debian's repos :/

We had a bug on main last night - it was fixed in https://github.com/chatmail/relay/pull/599. To resolve your issue, run `apt remove dovecot-core dovecot-imapd dovecot-lmtpd` on your server, and upgrade chatmail with `git pull --rebase --autostash` and `cmdeploy run` as usual.
