### ISSUE TITLE
IP address is determined incorrectly

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#336]
Maybe we should not try to determine IP address at all?

Here LAN address was determined by the script:
https://support.delta.chat/t/how-to-handle-private-ip-and-missing-ipv6-in-dns-configuration-for-chatmail-deployment-on-oci-cloud/3173

A records are set up already anyway since SSH is working. IPv6 should be optional.

PTR record checks we can drop completely I think, this practice of checking PTR records is even worse than DMARC itself and we should stop encouraging it: https://datatracker.ietf.org/doc/html/draft-ietf-dnsop-reverse-mapping-considerations-06

**Comment by hpk42** [comment]
how about we check

- at start of 'run'  serverside via `socket.getaddrinfo(mail_domain", None, socket.AF_INET*)` if we can resolve ipv4 and/or ipv6 address and bail out if not.  
- at end of 'run' the  reverse PTR records and give an interoperability warning if they don't resolve correctly but exitcode remains 0

**Comment by hpk42** [comment]
as you wrote the issue, it's not just reverse-dns but also about ip-address detection, no?

**Comment by hpk42** [comment]
#348 removed the need for reverse PTR, and there is no attempt to automaticlaly detect A AAAA records (which are required to be set now).
