### ISSUE TITLE
Upgrading pip modules before deploying?

### ISSUE THREAD

**Issue by jagtalon** [deltachat/chatmail#376]
I recently ran into a deploying issue where `cmdeploy run` showed the following error when deploying the main branch:

```
jag@chika ~/chatmail (main)> scripts/cmdeploy run
[ssh] login to chika.aangat.lahat.computer
Collecting initial DNS settings.............
[$ pyinfra --ssh-user root chika.aangat.lahat.computer /home/jag/chatmail/cmdeploy/src/cmdeploy/deploy.py -y]
Usage: pyinfra [OPTIONS] INVENTORY OPERATIONS...
Try 'pyinfra --help' for help.

Error: No such option: -y
Traceback (most recent call last):
  File "/home/jag/chatmail/venv/bin/cmdeploy", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 328, in main
    res = args.func(args, out, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 69, in run_cmd
    retcode = out.check_call(cmd, env=env)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jag/chatmail/cmdeploy/src/cmdeploy/cmdeploy.py", line 237, in check_call
    return subprocess.check_call(arg, shell=True, env=env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pyinfra --ssh-user root chika.aangat.lahat.computer /home/jag/chatmail/cmdeploy/src/cmdeploy/deploy.py -y' returned non-zero exit status 2.
```

It seems that pyinfra didn't understand `-y` and it looked like that was a new option based on the [changelogs](https://github.com/pyinfra-dev/pyinfra/releases/tag/v3.0). Running the version of pyinfra shows:

```
jag@chika ~/chatmail (main) [1]> venv/bin/pyinfra --version
pyinfra: v2.9.2
```

So I ran `$ venv/bin/pip install --upgrade pyinfra` and everything worked. I was wondering if perhaps `cmdeploy run` can update dependencies before deploying?

Thank you!

**Comment by mnarecki** [comment]
I've just stumbled upon the same problem. And I also had to upgrade pyinfra, otherwise I couldn't run deploy on my machine (Ubuntu 22.04). Thanks for opening an issue!

**Comment by missytake** [comment]
I think we should add the `-y` depending on the pyinfra version, we shouldn't require admins to think about the local dependencies or come up with the idea of upgrading them without any helpful error message.

**Comment by abixadamj** [comment]
I can only say that : `venv/bin/pip install --upgrade pyinfra` works ;-)
