### ISSUE TITLE
The SMTP TLS cert of Testrun.org is expired

### ISSUE THREAD

**Issue by vmon** [deltachat/chatmail#409]
As per "Connection status" log in the app:

`Outgoing Messages
 Error: SMTP connection failure: STARTTLS upgrade failed: unexpected EOF (certificate has expired): error:80000002:system library:file_open:reason(2):providers/implementations/storemgmt/file_store.c:263:calling stat(/usr/local/ssl/certs), error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2092:`

**Comment by hpk42** [comment]
testrun.org is not a chatmail server but thanks anyway (some testrun.org admins read this here).

To replicate: 

$ openssl s_client -starttls smtp -connect testrun.org:25 

which indeed results in an expired certs, details: 

```

Certificate chain
 0 s:CN = testrun.org
   i:C = US, O = Let's Encrypt, CN = R11
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jun 11 13:20:25 2024 GMT; NotAfter: Sep  9 13:20:24 2024 GMT
 1 s:C = US, O = Let's Encrypt, CN = R11
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 13 00:00:00 2024 GMT; NotAfter: Mar 12 23:59:59 2027 GMT

```

**Comment by Gh0stz0x** [comment]
👍

**Comment by missytake** [comment]
Fixed it.

**Comment by Gh0stz0x** [comment]
❤️
