### ISSUE TITLE
acmetool: private key is world-readable ?

### ISSUE THREAD

**Issue by feld** [deltachat/chatmail#415]
After I solved #414, the next step was to run `./scripts/cmdeploy dns`

This showed an error indicating it's forcing my private key to be world-readable!

```
> ./scripts/cmdeploy dns
[ssh] login to chat.example.com
Collecting initial DNS settings............20240924144438 [WARN] fdb: "live/chat.example.com/privkey" has wrong mode -r--r----, changing to -rw-r--r--
20240924144438 [CRITICAL] acmetool: fatal: storage: readlink /var/lib/acme/live/chat.example.com: invalid argument
...
Check expected zone file entries.........................................
Please set required DNS entries at your DNS provider:

(REDACTED)
```

This is a fairly serious local security violation, please correct this.

**Comment by hpk42** [comment]
@feld do you think it's still worthwhile to ensure non- world readability?  We can probably fix it but not sure it's worth it. If someone can get to the dir then they can probably also read the file whatever the mode?

**Comment by feld** [comment]
> `/var/lib/acme/keys`

that's not where the private key for the certificate is stored; it's `/var/lib/acme/live/DOMAIN/privkey`

I believe /var/lib/acme/keys are the keys for your acme account(s). So last I checked `privkey` was world-readable, but I'm not using acmetool at the moment. I'll need to deploy chatmail with cmdeploy on a fresh server to verify.
