### ISSUE TITLE
Temporary authentication failures on SMTP

### ISSUE THREAD

**Issue by link2xt** [deltachat/chatmail#441]
SMTP fails with errors like "SMTP failed to connect and authenticate: SMTP failed to login: transient: 4.7.0 Temporary authentication failure: Connection lost to authentication server." on CI.
This does not seem to happen on IMAP since #59 is fixed with #60.

Postfix has this in the logs:
```
Oct 29 22:32:48 c2-new postfix/smtps/smtpd[938095]: warning: unknown[127.0.0.1]: SASL PLAIN authentication failed: Connection lost to authentication server, sasl_username=(unavailable)
```

Apparently Dovecot is unhappy with too many auth connections from postfix?

There is some related thread suggesting that this happens because of too many connections from the same IP:
https://www.dovecot.org/list/dovecot/2012-May/135485.html
This happens both because on port 443 we hide the IP from postfix (and in turn dovecot) due to nginx proxy and just because a lot of connections come from GitHub Actions runners.

**Comment by missytake** [comment]
both dovecot-anvil and fail2ban seem to only be able to limit authentication tries by IP address, not be login username.

For now I would just disable the anvil penalty as recommended on the dovecot mailing list.

We could monitor failed login attempts per address in doveauth by incrementing some counter in the vmail directory, and if it's bad we can implement a delay on that ourselves... but we can also just increase `password_min_length` or something, that should already discourage attackers.
