### ISSUE TITLE
Tests failed and problem with chats

### ISSUE THREAD

**Issue by foozzi** [deltachat/chatmail#457]
- Server: Debian 12, Client: IOS 18.1
- Delta Chat Version: 1.48.3
- Expected behavior: tests passed
- Actual behavior: tests failed, chats problem
- Steps to reproduce the problem: Clean install on debian 12 and then run tests
- Screenshots: 
![IMG_5563](https://github.com/user-attachments/assets/b4cec9cb-d6f0-488c-a0b2-39b2e924804f)
- Logs: https://privatebin.net/?382d21380e049e7e#5wf2j799fFWwGSntyawipVS2NNiv75Z39s8QjrU26CXw
- Tests logs: https://privatebin.net/?f414d3425bad3289#ySYrLhhebnxe5maE4ZXPC4TiB9ExvNbGTsfWBUAgoM4
- dns: https://privatebin.net/?e9e22218780fa070#AatY1PEbhEhxEEdYTk3Meg2nTUG31NiR6n1xvqyPu1KK
- dovecot logs: https://privatebin.net/?45755137c64872cb#2myFBPz4HXnVQ9x35Rq1Wd88pbJcwApbphQRadMkEt35

There is interesting thing: 
```bash
----------------------------------------------------------- Captured stdout call -----------------------------------------------------------
$ dig
$ apt-get install -y dnsutils
----------------------------------------------------------- Captured stderr call -----------------------------------------------------------
/bin/sh: line 1: dig: command not found
/bin/sh: line 1: apt-get: command not found
```
but dig is already installed and of course apt-get

**Comment by missytake** [comment]
Can you send me your domain name to <sysadmin@testrun.org>, if it isn't `delta.mysite.pub`? Then I can test for myself... my best guess is that the DNS records are not in order and therefore other chatmail servers refuse to accept mails from yours.

**Comment by foozzi** [comment]
> Can you send me your domain name to [sysadmin@testrun.org](mailto:sysadmin@testrun.org), if it isn't `delta.mysite.pub`? Then I can test for myself... my best guess is that the DNS records are not in order and therefore other chatmail servers refuse to accept mails from yours.

did it

**Comment by missytake** [comment]
Hm, your server can receive mail just fine, and internal email also works... but sending messages to other servers via SMTP doesn't seem to work, they just don't arrive.

My best guess is that your hoster might be blocking you from sending SMTP traffic? njal.la blocks outgoing SMTP traffic for example, to avoid becoming a spam haven... of course that makes self-hosting federated email impossible with such hosters -.- which hoster are you using?

Some hosters only allow outgoing SMTP after some time, when an account has built up some trust. Or you might contact them and ask them to unblock it.

**Comment by missytake** [comment]
Another idea is to implement SMTP relaying to port 443 on chatmail servers... we already accept SMTP & IMAP connections on port 443, and Delta Chat is able to connect to port 443. Convincing postfix to try port 443 instead of port 25 might be difficult though^^

**Comment by missytake** [comment]
They say you can open a support ticket: https://docs.vultr.com/what-ports-are-blocked?lang=en&gspk=dHJveWNsYXJrNzM4Ng&gsxid=wQpnVuVRFBud

**Comment by hpk42** [comment]
nothing left to do for this issue, so closing.  For more questions/chat please use the sysadmin address provided by missitake.
