### ISSUE TITLE
Config issue: some messages for initial contact seem to be sent without TLS (PGP still used so probably not a direct security issue)

### ISSUE THREAD

**Issue by ell1e** [deltachat/chatmail#459]
There seems to be some chatmail config issue. When a friend of mine was picking up delta chat and wanted to add me as a friend, not via QR code but by just entering my e-mail via search, he got this error message when first trying to contact me:
> Sent: 2024.12.05 18:19:15 by Me (REDACTEDEMAIL@nine.testrun.org)
> State: Failed
> Error: Permanent SMTP error: permanent: Invalid unencrypted email to 
\<el@horse64.org\>
> Message-ID: REDACTEDMESSAGEID@localhost
>
> No Hop Info

Therefore, it seems sometimes messages for initial contact seem to be sent without TLS. While I assume PGP is still used, so this probably isn't a direct security issue, this still seems unfortunate.

My e-mail server that was targeted here doesn't accept non-TLS messages, which is why it didn't arrive. However, I don't think the chatmail server should have tried to send it as non-TLS message. When the user contacted me after that, it was sent via TLS and arrived perfectly fine.

My apologies if there is a potential issue on my side that I'm not aware of.

- Operating System (Linux/Mac/Windows/iOS/Android): unknown (other user)
- Delta Chat Version: seems to be chatmail mail server issue
- Expected behavior: e-mails are always sent via TLS
- Actual behavior: e-mails are sometimes not sent via TLS
- Steps to reproduce the problem: sign up as new chatmail user, add somebody else via e-mail search and not via QR code as an unverified new contact, send an initial message to your new contact
- Screenshots:
- Logs:

**Comment by missytake** [comment]
Hi, it's actually the other way around - TLS would be used, but chatmail blocks the outgoing message because PGP encryption is not available as long as he does not have your key. chatmail blocks outgoing messages if they are not PGP-encrypted for spam prevention reasons.

He can get your key by either scanning your QR code (or you scanning his), or either of you clicking on each other's invite link - that would be the normal way to establish [guaranteed end-to-end encryption](https://delta.chat/help#howtoe2ee). 

If that is not available to you, assuming you are using a regular email server which allows unencrypted outgoing messages, you can add his email address manually and send him an unencrypted message (which will have your PGP key in the Autocrypt header), then he will be able to reply encrypted.

**Comment by ell1e** [comment]
So the user discovery by email doesn't work for chatmail users? It sounds a little like it doesn't.

**Comment by ell1e** [comment]
If I understand right then for chatmail it's the **only** way, isn't it? That seems a bit unfortunate, since discovery by e-mail sounds useful for many scenarios and it doesn't seem to be compatible with this quirk. Perhaps there is a potential common ground, for example by allowing non-PGP mails if the target e-mail has been previously seen as a DeltaChat user by the chatmail server(s) at any point. My apologies if I'm misunderstanding something.

**Comment by hpk42** [comment]
On Mon, Dec 09, 2024 at 09:18 -0800, Ellie wrote:
> If I understand right then for chatmail it's the **only** way, isn't it? That seems a bit unfortunate, since discovery by e-mail sounds useful for many scenarios and it doesn't seem to be compatible with this quirk. Perhaps there is a potential common ground, for example by allowing non-PGP mails if the target e-mail has been previously seen as a DeltaChat user by the chatmail server(s) at any point. My apologies if I'm misunderstanding something.

Before we went for "only allow to send pgp-encrypted mail out" 
we indeed considered some form of tracking (different but related to what you suggest)
but it is tricky to get right, and also defeats the design goal for chatmail servers
to be very forgetful and not memorize any metadata. 

There are two ways to stablish end-to-end encryption: 

- using invite links/qr codes ("securejoin" protocols) 

- using vcards ("attach" contact in delta chat) -- they are also
  compatible with Proton Mail's vcards that also contain PGP keys btw

Note also that chatmail addresses are pretty random and we don't really
expect users to memorize their addresses and tell them to other people. 

There is no actionable item for this issue, so i am closing it. 
(note btw that chatmail servers *enforce* also TLS, both outgoing and incoming)

**Comment by ell1e** [comment]
This isn't really about enforcing TLS though, is it? It's about contacting new users.

**Comment by hpk42** [comment]
On Tue, Dec 10, 2024 at 05:08 -0800, Ellie wrote:
> I think if e-mail discovery is not meant to work at all for chatmail users searching for regular non-chatmail users, it might be worth at the very least showing a warning dialog when chatmail users try to use it. But this seems like a pretty basic feature so I hope it'll be fixed.

Delta Chat already shows a warning (see attachment, from desktop install) when one tries to mail 
to someone and e2e-encryption is not availble.

**Comment by hpk42** [comment]
![Screenshot from 2024-12-10 14-48-45](https://github.com/user-attachments/assets/d862f9ea-3e44-4961-adfa-1fc0c7cb44a8)

**Comment by ell1e** [comment]
Interesting! I had one user run into this anyway, now I wonder if somehow the warning didn't work for them or what happened. I agree that the warning seem to be fairly visible.

**Comment by hpk42** [comment]
On Tue, Dec 10, 2024 at 05:56 -0800, Ellie wrote:
> Interesting! I had one user run into this anyway, now I wonder if somehow the warning didn't work for them or what happened. I agree that the warning seem to be fairly visible.

not sure the warning comes on all devices like this. 
It's a rough corner -- so if you have any specifics, please tell but better
open a new issue then on the respective repository.

**Comment by ell1e** [comment]
I'm still wondering how this could possibly be fixed. What if non-chatmail users could opt-in to chatmail e-mails in some way? Some e-mail discovery option, that goes from "Disable" to "Enable (safe, excluding anonymous chatmail)" to "Enable (full)" or something. Then the users opting in would somehow contact the chatmail server to store their address on a whitelist.

**Comment by hpk42** [comment]
On Tue, Dec 10, 2024 at 06:05 -0800, Ellie wrote:
> I'm still wondering how this could possibly be fixed. What if non-chatmail users could opt-in to chatmail e-mails in some way? Some e-mail discovery option, that goes from "Disable" to "Enable (limited, excluding anonymous chatmail)" to "Enable (full)" or something. Then the users opting in would somehow contact the chatmail server to store their address on a whitelist.

there are many different chatmail servers so this wouldn't work. 
Making chatmail servers allow unencrypted messaging goes a bit against 
ensuring privacy and e2e-encryption -- it's really better to use some
non-chatmail server then and not complicate the current logic which works
pretty simply and predictably.

**Comment by ell1e** [comment]
So then why does the e-mail discovery even exist? It seems slightly conflicting from a design perspective. Given that the QR code UI can be clumsy on desktop and often the QR codes will be transmitted insecurely themselves, I'm not quite sure if that's really worth pushing the users into if they know there is currently no good way to ensure a verified connection. IMHO there is some use in allowing explicitly non-verified contacts, which is also why I suggested in some other places that when scanning a QR code, a prompt whether I even trust the code's origin would be useful.

For what it's worth, the user just confirmed they were using the desktop client and didn't consciously notice the warning. So either it wasn't working, or perhaps it was too subtle for them.

**Comment by hpk42** [comment]
i understand and appreciate you are trying to find a way to expand the usefullness
of chatmail servers. 
But any heuristic we might introduce for allowing to send out unencrypted mails 
opens up to potential abuse by spammers who write scripts automating 
creation of accounts and then clear the heuristic hurdle and use it
to send out spam, which gets the chatmail server blocked. 
So far chatmail server have a pretty good track record 
interacting with the wider e-mail system.
